### ISSUE TITLE
Android non-organic installs

### ISSUE THREAD

**Issue by alexbaforvo** [AppsFlyerSDK/appsflyer-nativescript-plugin#12]
Using the android SDK Integration test app, it reports that the integration test is OK, but I cannot see non-organic installs in the dashboard, but I see the click count rise with every test.

```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.0.1 version and is up to date.
✔ Component tns-core-modules has 4.0.0 version and is up to date.
✔ Component tns-android has 4.0.1 version and is up to date.
✔ Component tns-ios has 4.0.1 version and is up to date.
```

I see organic installs and track_events but no result for non-organic installs

**Comment by af-fess** [comment]
Please set `isDebug` true and post the logs. thanks
