### ISSUE TITLE
Nativescript 6.5, Angular, Android not working

### ISSUE THREAD

**Issue by Bidou44** [AppsFlyerSDK/appsflyer-nativescript-plugin#27]
I just installed the latest version of the plugin  "nativescript-plugin-appsflyer": "~5.2.1".
 
It works on iOS but not on Android. I have no error in the logs, the trackEvent respond with "successfull" but on Android I don't see any entries in appFlyers.
I'm using Nativescript 6.5 with Angular.

Here my code (working on iOS)

**main.ts**
```
const appsflyerOptions: appsFlyer.InitSDKOptions = {
    devKey: 'XXX',
    appId: application.ios ? 'XXX' : null,
    isDebug: !environment.isProd
};

appsFlyer.initSdk(appsflyerOptions).then(() => {
    console.log('AppFlyer successfully initialized');  //<- I see this in the console
}, err => {
    console.warn('Could not initialize AppFlyer', err);
});
```

**home-page.component.ts**
```
appsFlyer.trackEvent({
        eventName: 'test',
        eventValues: {
            'af_content_id': 'id123',
            'af_currency': 'CHF',
            'af_revenue': '2.5'
}).then(result => {
        console.log('AppFlyers tracked event successfully'); // <- I see this in the console
}, err => {
        console.log('Error while tracking event in AppFlyers');
});
```

**Comment by GM-appsflyer** [comment]
Hey Bidou44,

I was unable to reproduce the issue, and I was able to find the events on our servers.

Please try using the **SDK integration tests** page located in the AppsFlyer dashboard.
First, generate a non-organic install as the first test, and continue to the in-app event test by following the instructions. 

To continue this conversation please contact us via support@appsflyer.com

**Comment by Bidou44** [comment]
Hey @GM-appsflyer 

I did the following now:
1) Checkout your demo code
2) npm run setup
3) npm run demo.android

The application starts and when I click on the "trackEvent" button, everything is green. I didnt check if the event was create, I dont think that I can access the account to verify it....

Then:
4) Replace the devKey with mine (I'm sure that my devKey is correct since it's working on iOS)
5) I let your appId since it should not play any role for android (according to your documentation)
6) npm run demo.android

The application starts and when I click on the "trackEvent" button, I get an exception:

> JS: AppsFlyer :: NativeScript :: trackAppLaunch is called
> System.err: An uncaught Exception occurred on "main" thread.
> System.err: Calling js method onConversionDataFail failed
> System.err: Error: java.lang.AbstractMethodError: abstract method "void com.appsflyer.AppsFlyerConversionListener.onConversionDataFail(java.lang.String)"
> System.err: 
> System.err: StackTrace:
> System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
> System.err: 	at com.tns.Runtime.access$2300(Runtime.java:39)
> System.err: 	at com.tns.Runtime$5.run(Runtime.java:1307)
> System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
> System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> System.err: 	at android.os.Looper.loop(Looper.java:164)
> System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> System.err: 	at java.lang.reflect.Method.invoke(Native Method)
> System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> System.err: Caused by: java.lang.AbstractMethodError: abstract method "void com.appsflyer.AppsFlyerConversionListener.onConversionDataFail(java.lang.String)"
>

**Comment by Bidou44** [comment]
The problem was that I had to change the id of the app in the package.json !

Please, update your documentation and write this explicitly. Also, having different way to do this on iOS and Android is not the best design choice in my opinion.....

**Comment by GM-appsflyer** [comment]
Hey Bidou44,

Thank you for providing the feedback, we'll update our documentation and work on fixing the bug mentioned!

The reason the App ID is set differently is that on Android, the App ID is the Package name.
When compiling native script to an Android native project the package name is created based on the package JSON file. This behavior is similar to other platforms like React-Native, Cordova.
and etc.

Kindly open a ticket in support@appsflyer.com if you have any further questions regarding the same matter or reach out to us if you have any further technical queries/issues in the future and we will be happy to assist.

Thank you and have a good day!
