### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzg;

### ISSUE THREAD

**Issue by fllaryora** [AppsFlyerSDK/appsflyer-nativescript-plugin#32]
Hello,  Good morning:

I am integrating my application with this plugin: 

I installed the plugin with: `tns plugin add nativescript-plugin-appsflyer`

 That added In the dependencies object in package.json:
`"nativescript-plugin-appsflyer": "^5.2.2",` 

I my app.component.ts I call :  

`appsFlyer.initSdk(options).then(function(result) {
                       console.log("intSDKresponse!!!!!!!!!!!!@@@@@@@@@@@@@@@@@@@@@@@: " + result.status );
        }, function(err) {
            console.warn("initSDKresponse!!!!!!!!!!!@@@@@@@@@@@@@@@@: " +JSON.stringify(err));
        });`

with my devkey and appId given from my dashboard.

After that I run: 
`tns run android`

My build is successfully but when I start my application I am getting the following stack-trace:

`JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Fetching.....
JS: AppsFlyer :: trackAppLaunch is called
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: intSDKresponse!!!!!!!!!!!!@@@@@@@@@@@@@@@@@@@@@@@: success
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{com.some.foo.package/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzg;
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.some.foo.package/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzg;
System.err:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3139)
System.err:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3282)
System.err:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:    at android.os.Looper.loop(Looper.java:214)
System.err:    at android.app.ActivityThread.main(ActivityThread.java:7156)
System.err:    at java.lang.reflect.Method.invoke(Native Method)
System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzg;
System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:    at com.tnsome.foo.packageonCreate(NativeScriptActivity.java:19)
System.err:    at android.app.Activity.performCreate(Activity.java:7335)
System.err:    at android.app.Activity.performCreate(Activity.java:7326)
System.err:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
System.err:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3119)
System.err:    ... 11 more
System.err: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzg;
System.err:    at com.google.android.gms.ads.internal.client.zzm.zzjs(Unknown Source:0)
System.err:    at com.google.android.gms.ads.internal.client.zzag.zza(Unknown Source:11)
System.err:    at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:12)
System.err:    at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1)
System.err:    ... 22 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamic.zzg" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", `

We tried to fix that by changing our version of google play

`googlePlayServicesVersion = "16.+"` 

with: 

`googlePlayServicesVersion = "+"` 

but that does not fix the issue.

Could you give me a clue? How can we fix it?

**Comment by GM-appsflyer** [comment]
Hey,

I've replied to the ticket under the support@appsflyer.com.

I'll be closing this thread.
