### ISSUE TITLE
Support for Angular10

### ISSUE THREAD

**Issue by ragu89** [AppsFlyerSDK/appsflyer-nativescript-plugin#37]
The plugin is not working on iOS with [Angular10](https://nativescript.org/blog/angular-10-support/).

Error message is :
`file: node_modules/nativescript-plugin-appsflyer/appsflyer.ios.js:4:0: JS ERROR TypeError: undefined is not an object (evaluating 'utils_1.ios.collections')`

I have create a [project example](https://github.com/AppsFlyerSDK/appsflyer-nativescript-plugin/files/5108775/ns-angular10-appflyers.zip)

This project has been created with the following procedure :
- Upgrade nativescript to RC : `npm i -g nativescript@rc`
- Create a default helloworld project : `nsc create sampleapp --template @nativescript/template-hello-world-ng`
- Adding an entry in the `package.json` for` nativescript-plugin-appsflyer `version 5.2.2
- Adding a call to the method `trackEvent` in the items.component class
- run `npm i`
- run `tns run ios`

**Comment by NathanWalker** [comment]
@ragu89 You can keep an extra branch if you want to maintain a 6.5.x series and older version around. The main difference is the import path is simplified to 1 single barrel for all (@nativescript/core) vs. having many different deep import paths.
You could branch current master to `tns-core-modules` branch and that could become the 6.5.x series and master can become the PR posted. that allows you to merge changes between the 2 (or you can do it inversely where the NativeScript 7+ compatible version is on a branch and you maintain the older on master.

**Comment by limux82** [comment]
@NathanWalker In the plugin migration page to nativescript 7 I see that is available the version 6.0.0, but it's not available in npm https://nativescript.org/blog/nativescript-7-compatible-plugins/

Do I have to change namespace to @nativescript/plugin-app-flyer?
