### ISSUE TITLE
Version 5.4.2 - Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by limux82** [AppsFlyerSDK/appsflyer-nativescript-plugin#39]
I have this error installing the new version 5.4.2. In the node-module folder of the package there is a .git folder. Deleting it then it works. Is it possible to  resolve the problem with a new build?

npm ERR! path /node_modules/nativescript-plugin-appsflyer
npm ERR! code EISGIT
npm ERR! git /node_modules/nativescript-plugin-appsflyer: Appears to be a git repo or submodule.
npm ERR! git  /node_modules/nativescript-plugin-appsflyer
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

**Comment by GM-appsflyer** [comment]
Please open again of this is still relevant
