### ISSUE TITLE
logEvent promise will not resolve on Android when onSuccess/onError not specified

### ISSUE THREAD

**Issue by jalberto-ghub** [AppsFlyerSDK/appsflyer-nativescript-plugin#48]
If you do not pass call backs for either `onSuccess` and/or `onError` on `logEvent()` the promise is never resolved.
Version:     "nativescript-plugin-appsflyer": "6.2.3",

Just try the following:

```
{
   await appflyer.logEvent({ eventName: "af_login", eventValues: null});
   // You will never reach here on your code
}

```

**Comment by GM-appsflyer** [comment]
Hey @jalberto-ghub ,

We're investigating this issue. We'll update here once fixed.

**Comment by GM-appsflyer** [comment]
Hey @jalberto-ghub ,
I've fixed the issue in latest version.
Please let us know if there is anything else we can help with!
