### ISSUE TITLE
Plugin will not accept using "@nativescript/core": "7.1.4"

### ISSUE THREAD

**Issue by jalberto-ghub** [AppsFlyerSDK/appsflyer-nativescript-plugin#49]
"nativescript-plugin-appsflyer": "6.2.3" depends on "@nativescript/core": "~7.0.0" however there are now important fixes to NS that require versions above "7.0.x". The latest core is now "7.3.0"

Some strict versions of NPM will error out when the dependency restriction is not satisfied.

**Comment by GM-appsflyer** [comment]
Hey,

We'll work on updating the native script version soon.

**Comment by GM-appsflyer** [comment]
Hey @jalberto-ghub ,

I've update the plugin to NS V8.
Please let us know if everything is working as expected!

**Comment by jalberto-ghub** [comment]
Hi @GM-appsflyer can you tweak the NS version dependencies of the plugin so it can accept N7 & N8 platforms? I do not think the plugin is using any new specific feature from N8.
The problem is that N8 is still in beta release and it is not suitable for us for production release.
Can you set up some more lenient dependencies that allow for both major versions?

Here is a guide to the version syntax:
https://flaviocopes.com/package-json/#package-versions

**Comment by GM-appsflyer** [comment]
We've published v6.2.4-2
This should support NS version 7.0.0 or higher
