### ISSUE TITLE
Missing support of UDL deep-links for new and existing users

### ISSUE THREAD

**Issue by jalberto-ghub** [AppsFlyerSDK/appsflyer-nativescript-plugin#50]
There is no support to implement UDL links for new and existing users.
For Android the plugin does not support versions 6.1+ as required for dynamic links.
There is no access on the plug-in API to the DeepLinkListener that is required to listen to UDL links.

Is there a time frame for upgrading this plug-in?

**Comment by GM-appsflyer** [comment]
Hey @jalberto-ghub ,

We'll work on adding a unified deep link to native script and upgrading the SDK version.

**Comment by GM-appsflyer** [comment]
hey @jalberto-ghub ,

We've added the UDL callback in v6.2.6-3
