### ISSUE TITLE
App Tracking Transparency (ATT) support

### ISSUE THREAD

**Issue by benedictstrube** [AppsFlyerSDK/appsflyer-nativescript-plugin#54]
With the release of iOS 14.5, tracking frameworks are only allowed to access a users IDFA after he/she gave his/her consent actively. For the iOS AppsFyler SDK, there is the [option to delay events](https://support.appsflyer.com/hc/en-us/articles/207032066#integration-33-configuring-app-tracking-transparency-att-support) (such as app installs) tracked with AppsFlyer until the user had the option to answer the dialogue asking for his consent to be tracked (and as a result, send those events **with** the IDFA from then on instead of sending them **without** IDFA until he gave his consent). However, I cannot find the option to do this in the Nativescript plugins API or documentation. Am I missing something?

In my understanding, it is really important to delay especially the app installs until the IDFA is accessible, to optimise advertisement campaigns. So it seems important, that events are delayed. When the option to delay events is not accessible in the plugin, is there another way? Like initialising the plugin **after** asking for consent? Does this also delay events?

**Comment by GM-appsflyer** [comment]
Hey @benedictstrube ,

Thank you for reaching out!
We're working on adding the waitForATTUserAuthorization API:
https://support.appsflyer.com/hc/en-us/articles/207032066#integration-33-configuring-app-tracking-transparency-att-support

Hopefully this week!

**Comment by bergerbyte** [comment]
Hi, is there anything new yet?

**Comment by GM-appsflyer** [comment]
Hey @bergerbyte ,
I believe next week this API will be added.

Thank you for your patience!

**Comment by GM-appsflyer** [comment]
Hey @bergerbyte ,
waitForATTUserAuthorization API was added in v6.2.6-2.
Here is a quick guide on how to set NS for iOS 14:
https://github.com/AppsFlyerSDK/appsflyer-nativescript-plugin#ios14
