### ISSUE TITLE
Illegal code TS1174: Classes can only extend a single class.

### ISSUE THREAD

**Issue by mattbushell** [AppsFlyerSDK/appsflyer-nativescript-plugin#65]
This line is illegal and wont pass linting/language validation, using TS 3.9.7 NS7

We must remove the ATTrackingManager in order for apps based on this code to compile. Having looked into the "typings" lib im not sure why it needs to use MI here, seems like nonsense.

https://github.com/AppsFlyerSDK/appsflyer-nativescript-plugin/blob/1da53a14bd0f3d13c5650f379582d6b3af31d247/demoNative/app/custom-app-delegate.ios.ts#L2

**Comment by mattbushell** [comment]
Pretty sure the delegate doesnt need to extend UIResponder either

**Comment by GM-appsflyer** [comment]
Hey @mattbushell ,

This is the implementation for the app delegate for the demo project that uses: 
https://docs.nativescript.org/best-practices/native-class.html. 
For now, you can comment it out from the plugin as it is just an example of how to add AppsFlyer deep link methods and att consent dialog in the iOS life-cycles. 
We'll update the plugin so it will be optional.

**Comment by mattbushell** [comment]
Not sure why this is being so tricky to explain. The code is not legal TS NativeScript or not. Just load the class in an IDE or tsc in isolation, it will not compile. There is no mention of using incorrect TS in the nativescript docs you link.

extends UIResponder, ATTrackingManager

It is a simple fix so that your Demo app is not gibberish for new inexperienced users, and that is to remove the ATTTrackingResponder from the extends portion of the class def, and simply import it.

**Comment by GM-appsflyer** [comment]
Hey @mattbushell ,

Thanks for the feedback!
We've pushed a fix for this issue.
